In [1]:
import numpy as np

In [3]:
#SUB-ARREGLOS 
#los ejercicios a continuación seran del tema sub-arreglo

elementos = np.arange(1,21)
elementos
#crearemos un sub-arreglo de los numeros pares del arreglo anterior
pares = np.array([i for i in elementos if i%2==0])
pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
#Dado un array de 5x5 de números aleatorios, obtén un sub-arreglo con las filas 2 a 4 y las columnas 1 a 3.
#Arreglo 5x5
matrix = np.random.randint(1,50,25).reshape(5,5)
matrix
#sub-arreglo fila : 2-4,columna:1-3
sub_matrix = matrix[1:4] #selecionamos fila 2,3,4
for fila in sub_matrix:
    fila = fila[0:3]     #selecionamos columnas 1,2,3

print("\nsub-matrix:")
for fila in sub_matrix:
    print(fila)



sub-matrix:
[39 32 38 43 39]
[ 9 40 14 25  6]
[27 27 13 40 41]


In [14]:
#Dado un array de 1D con 50 elementos, obtén los últimos 10 elementos utilizando índices negativos.

#creamos el arreglo 
arreglo = np.arange(1,51)
arreglo
#utilazando negativos hacemos un sub-arreglo
sub_arreglo = arreglo[-10::]
sub_arreglo

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
#Genera un arreglo 2D (3x4) y extrae la segunda columna como un sub-arreglo.

#Arreglo 3x4
matriz = np.arange(1,13).reshape(3,4)
matriz
#sub-arreglo de la segunda columna
sub_arrg = matriz[1]
sub_arrg

array([5, 6, 7, 8])