In [7]:
import numpy as np

In [3]:
#SUB-ARREGLOS 
#los ejercicios a continuación seran del tema sub-arreglo

elementos = np.arange(1,21)
elementos
#crearemos un sub-arreglo de los numeros pares del arreglo anterior
pares = np.array([i for i in elementos if i%2==0])
pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
#Dado un array de 5x5 de números aleatorios, obtén un sub-arreglo con las filas 2 a 4 y las columnas 1 a 3.
#Arreglo 5x5
matrix = np.random.randint(1,50,25).reshape(5,5)
matrix
#sub-arreglo fila : 2-4,columna:1-3
sub_matrix = matrix[1:4] #selecionamos fila 2,3,4
for fila in sub_matrix:
    fila = fila[0:3]     #selecionamos columnas 1,2,3

print("\nsub-matrix:")
for fila in sub_matrix:
    print(fila)



sub-matrix:
[39 32 38 43 39]
[ 9 40 14 25  6]
[27 27 13 40 41]


In [14]:
#Dado un array de 1D con 50 elementos, obtén los últimos 10 elementos utilizando índices negativos.

#creamos el arreglo 
arreglo = np.arange(1,51)
arreglo
#utilazando negativos hacemos un sub-arreglo
sub_arreglo = arreglo[-10::]
sub_arreglo

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
#Genera un arreglo 2D (3x4) y extrae la segunda columna como un sub-arreglo.

#Arreglo 3x4
matriz = np.arange(1,13).reshape(3,4)
matriz
#sub-arreglo de la segunda columna
sub_arrg = matriz[1]
sub_arrg

array([5, 6, 7, 8])

In [8]:
#VECTORIZACION
#Diseña una función vectorizada que calcule el cuadrado de los elementos solo si son números pares.
def cuadra_pares(n:int)->int:   #creamos la funcion para calcular el cuadrado si es par
    if n % 2==0:
        return n**2
    else :
        return n

#creamo el arreglo que vamos a vectorizar
arreglo = np.random.randint(1,20,10) #Arreglo
arreglo_vectorizado = np.vectorize(cuadra_pares) # creamos una arreglo vectorizado,usando el metodo vectorize() 

arreglo_vectorizado(arreglo) #vectorizamos el arreglo

    


array([196,  19,  64,   7,  15, 100,  17, 256,   5,   9])

In [12]:
#Vectoriza una función que convierta un número en su representación binaria.
#creamos la funcion para convertir decimal a binario
def conversion_a_binario(numero:int)->str:
    binario = ""
    while numero >0:
        resiudo = numero % 2
        binario = str(resiudo) + binario
        numero //=2
    return binario

#creamos el arreglo y vectorizamos con la funcion
elementos = np.random.randint(1,25,10)
elemento_vector = np.vectorize(conversion_a_binario)

elemento_vector(elementos)

array(['1101', '10111', '101', '10101', '10110', '100', '1100', '1001',
       '1001', '10100'], dtype='<U5')

In [19]:
#Crea una función vectorizada que identifique si un número es primo.
#funcion para identificar si es primo
def identificador_primos(numero:int) -> str:
    if numero %2 !=0:
        return 'primo'
    else: 
        return numero

#creamos el arreglo y vectorizamos 
arreglo = np.random.randint(1,20,10)
vector_arreglo = np.vectorize(identificador_primos)

vector_arreglo(arreglo)


array(['primo', '2', 'primo', 'primo', '14', '12', '16', '12', '18', '16'],
      dtype='<U5')

In [21]:
#Diseña una función vectorizada que tome dos arreglos de igual tamaño y devuelva el mayor elemento de cada posición.
def maximo_elemento(x:int,y:int) -> int: #funcion para identificar el maximo de cada elemento
    return max(x,y)

arreglo_1 = np.random.randint(1,20,10) # creamos los arreglos con la misma longitud de numeros
arreglo_2 = np.random.randint(1,20,10)

arreglo_vector = np.vectorize(maximo_elemento) #vectorizacion de la funcion 

arreglo_vector(arreglo_1,arreglo_2) #output


array([18, 12, 16, 19, 17, 14,  7, 11, 12,  9])